using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DiceTest : MonoBehaviour
{

    public int testint = 0;
    public int DiceResult;

    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.J))
        {
            DiceManager.GetInstance.DelayedRoll(testint, OnDiceResult);
            //Debug.Log($"κ°’: {DiceResult}");
        }
    }

    public void RollDice(int result)
    {
        DiceResult = result;
    }

    private void OnDiceResult(int result)
    {
        Debug.Log("μ£Όμ‚¬μ„ κ²°κ³Ό: " + result);

        if (result == 77)
        {
            Debug.Log("π² μ„Έ μ£Όμ‚¬μ„κ°€ κ°™μ! νΉμ μ΄λ²¤νΈ λ°μƒ");
        }
        else if (result >= 12)
        {
            Debug.Log("ν° μκ°€ λ‚μ™€μ„ κ°•λ ¥ν• μ•΅μ… κ°€λ¥!");
        }
        else
        {
            Debug.Log("μ‘μ€ μ... μ΅°μ‹¬ν•΄μ•Ό ν•¨.");
        }
    }
}
